---
title: "淋巴瘤(C33-34)"
registry: "2022河南省"
report: "肿瘤登记年报"
year: 2022
execute: 
  echo: false
  message: false
  warning: false
mainfont: "Lantinghei SC"
format:
  fact-typst:
    height: 524.3mm
    width: 370.5mm
    header-color: rgb(159,70,60)
---

```{r}
library(canregtools)
library(manuscript)
library(ggcanreg)
library(ggplot2)
library(dplyr)
cancer_code <- "103"
cancer_des <- tidy_var(cancer_code, var_name = "cancer", label_type = "abbr", lang = "cn")
```

```{r}
asr_inci <- create_asr(canregs[[1]], sex, cancer)
asr_mort <- create_asr(canregs[[1]],sex, cancer, event = "sws")
```


```{r}
#| output: asis
#| layout-ncol: 2
asr1 <- asr_inci |>
  cr_filter(cancer == cancer_code, sex == 0)
asr2 <- asr_mort |>
  cr_filter(cancer == cancer_code, sex == 0)
cr_summary_block(asr1, fill = "blue")
cr_summary_block(asr2, type = "mortality")
```



### 恶性肿瘤顺位

```{r}
#| output: asis
#| layout-ncol: 2

cr_bar_text(text = "发病率", border_color = "blue", inset_y = "0.1em",
            border_size="0.2em",text_size = "25pt", margin = "1em")
cr_bar_text(text = "死亡率", border_color = "red", inset_y = "0.1em",
            border_size="0.2em",text_size = "25pt", margin = "1em")
```



```{r}
#| fig-height: 2
#| layout-ncol: 1
dat <- asr_inci |>
  mutate(type = "发病率") |> 
  bind_rows(asr_mort |> 
              mutate(type = "死亡率")
            ) |> 
  cr_filter(sex == 0, drop = c("others", "total")) |> 
  add_labels(label_type = "abbr")

gg_barchart(dat, x = cancer_cn, y = cr, facet = type, ncol = 2, highlight = cancer_des)+
  theme_block()+
  #scale_x_continuous(position = "bottom") +
  theme(
    text = element_text(family="STSong", size = 6),
    legend.position = "none",
    axis.text.y = element_text(size = 4),
    axis.text.x = element_text(size = 4),
    strip.text = element_blank(),
    plot.title = element_text(hjust = 0, color = "gray40"),
    plot.margin = margin(0, 0, 0, 0, unit = "pt"))

```

{{<pagebreak>}}
